name: Development CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: read

    steps:
      - name: Debug GitHub Token
        run: |
          echo "Checking GitHub authentication..."
          curl -u "${{ secrets.GITHUB_ACTOR }}:${{ secrets.GH_PAT }}" -X GET https://maven.pkg.github.com/Renovatio-Coders/toolkit/

      - name: Checkout Repository
        uses: actions/checkout@v4.2.0

      - name: Set up JDK 21
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.5'

      - name: Build with Gradle Wrapper
        run: ./gradlew build

      - name: Upload Build Artifact (JAR)
        uses: actions/upload-artifact@v4.0.0
        with:
          name: build-artifacts
          path: build/libs/*.jar  # JAR 파일을 아티팩트로 저장
    env:
      GH_PAT: ${{ secrets.GH_PAT }}

  test:
    runs-on: ubuntu-22.04
    needs: build  # build가 성공한 후 실행됨
    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.5'

      - name: Run Tests
        run: ./gradlew test
    env:
      GH_PAT: ${{ secrets.GH_PAT }}

  publish:
    runs-on: ubuntu-22.04
    needs: [ build, test ]  # build & test가 성공한 후 실행됨
    permissions:
      contents: read
      packages: write  # GitHub Packages에 업로드하려면 필요

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.5'

      - name: Publish to GitHub Packages
        run: ./gradlew publish -Pversion=0.0.1-DEV-SNAPSHOT
    env:
      GH_PAT: ${{ secrets.GH_PAT }}