
name: Integration

on:
  push:
    branches: 
      - "feature/**"
      - "release/**"
      - "hotfix/**"
  pull_request:
    branches: 
      - "feature/**"
      - "release/**"
      - "hotfix/**"

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.0

      - name: Set up JDK 21
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.5'

      - name: Build with Gradle Wrapper
        run: ./gradlew build

      - name: Upload Build Artifact (JAR)
        uses: actions/upload-artifact@v4.0.0
        with:
          name: build-artifacts
          path: build/libs/*.jar  # JAR 파일을 아티팩트로 저장
